name: Build & Push Docker Image
on: []
jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: docker build .
